### ISSUE TITLE
Syntax Error: Cannot parse the unexpected character "/".

### ISSUE THREAD

**Issue by gex** [develomark/graphql-cli-generate-fragments#2]
i get this syntax error when using the `generate-fragments` command:
```
$ API_URL=foo AUTH_TOKEN=bar graphql generate-fragments -p default -g js -o baz --save
✖ Generating fragments for project default...
Syntax Error: Cannot parse the unexpected character "/".
```

my `.graphqlconfig`:
```
{
  "schemaPath": "schema.json",
  "extensions": {
    "endpoints": {
      "default": {
        "url": "${env:API_URL}",
        "headers": {
          "Authorization": "Bearer ${env:AUTH_TOKEN}"
        }
      }
    }
  }
}
```

i've successfully saved the schema file (with `graphql get-schema`) so the url and the token are valid.

from my `package.json`:
```
"graphql-cli": "^2.13.0",
"graphql-cli-generate-fragments": "^1.1.0",
```

**Comment by develomark** [comment]
Hi @gex super apologies for the delay - I've been on holiday. 

In your `.graphqlconfig` you have a json file. `schemaPath": "schema.json,`- This should be a graphql schema.

Did you run `graphql init`? 

If you follow the steps laid out in "see it in action" from: https://github.com/graphql-cli/graphql-cli you should be able to run `graphql get-schema` afterwards and then `graphql generate-fragments`

**Comment by develomark** [comment]
@gex How did you go?

**Comment by gex** [comment]
@develomark yep i was able to save the schema with `graphql get-schema` as i mentioned it in my previous comment:
> i've successfully saved the schema file (with graphql get-schema) so the url and the token are valid.

after i successfully run `graphql init` and `graphql get-schema` i got the syntax error with `graphql generate-fragments` :(

**Comment by develomark** [comment]
Can you share your `.graphqlconfig`? It shows `schemaPath": "schema.json`, as opposed to `schemaPath": "schema.graphql`

**Comment by develomark** [comment]
@gex Can you share with me your schema?

**Comment by gex** [comment]
they [added](https://github.com/graphql-cli/graphql-cli/pull/84/files) json output to `graphql-cli` and i thought `schema.json` would be more straightforward than storing json in a `schema.graphql` file. :)

i'm not allowed to post my schema publicly but if it helps i can share it with you.

**Comment by develomark** [comment]
I didn't know that - seems to be undocumented!

I wouldn't suggest that it is more straightforward. All the tooling pulls in `.graphql` files. graphql-tag, graphql-import etc. etc.

What is the usecase for json over graphql for the schema?

**Comment by gex** [comment]
to be honest i don't remember exactly why i switched to json. i tried to setup a lot of things together. i'm using apollo, v2 needs [fragment matching](https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/fragment-matching.md) so i installed `graphql-cli` with your plugin then i thought it would also be nice to validate all of my queries and mutations with `eslint-plugin-graphql` but i use `eslint-plugin-prettier` and those two are not compatible yet ([`eslint-plugin-graphql` #109](https://github.com/apollographql/eslint-plugin-graphql/issues/109) and [`eslint-plugin-prettier` #81](https://github.com/prettier/eslint-plugin-prettier/issues/81)). somewhere in this process i switched to json. :)

i switch back to graphql extension and try to get the fragments with that setup and get back to you with the results!

**Comment by develomark** [comment]
Under the hood this is passing SDL (the schema) via `importSchema()` and `passSDL()` from`graphql-import` - it doesn't have a method to pass JSON.

I'll update the error message for this so it now throws a more informative error message.

Thanks for the spot @gex

**Comment by develomark** [comment]
OK that's done.

Please update to the latest.

**Comment by gex** [comment]
thank you for your time and help!

**Comment by gex** [comment]
okay, now i remember why i switched to json:

1. `eslint-plugin-graphql` needs the schema in json format
2. [apollo documentation](https://www.apollographql.com/docs/react/recipes/fragment-matching.html) recommends _"setting up a build step that extracts the necessary information from the schema into a JSON file, where it can be imported from when constructing the fragment matcher"_ and i don't know why but i supposed this plugin will help me to extract that data from the schema but i was wrong :D

**Comment by develomark** [comment]
@gex Hey no problem.

FYI you don't need to have the schema in json for `eslint-plugin-graphql` I've got that working with SDL. It automatically picks it up from `.graphqlconfig`.
