### ISSUE TITLE
Error: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by paulcpk** [develomark/graphql-cli-generate-fragments#3]
Hi 👋 ,

when I run `graphql generate-fragments -p app` with the following configuration:
```{
  "projects": {
    "app": {
      "schemaPath": "schema.graphql",
      "extensions": {
        "endpoints": {
          "default": "http://localhost:3000/graphql"
        },
        "generate-fragments": {
          "output": "generated/graphql.fragments.js",
          "generator": "js"
        }
      }
    }
  }
}
```
I get an error `Cannot read property 'name' of null`.

My Schema is really large, for simplicity I tried to recreate the error with a simple example Schema:
```
# This works
type Post {
  id: ID!
  title: String!
  author: User
}

type Query {
  allPosts: [Post]
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  posts: [Post]!
}

```

```
# This throws an error
type Post {
  id: ID!
  title: String!
  author: User
}

type Query {
  allPosts: [Post]
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  posts: [Post]
}
```
The only difference here is the *non-nullable* array at `posts` in `type User`. 

This might be related to https://github.com/develomark/graphql-cli-generate-fragments/issues/2
Any Ideas on how to fix this?

Thanks!

**Comment by develomark** [comment]
@plck is that valid?

With graphcool/prisma lists cannot be defined like that, see: https://www.prismagraphql.com/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#required-relations

> Note that a to-many relation field is always set to required. For example, a field that contains many user addresses always uses the type [Address!]! and can never be of type [Address!]. The reason is that in case the field doesn't contain any nodes, [] will be returned, which is not null.

Or is this rule just specific to GC/Prisma?

If that is valid, I can fix this for you no problem. Also please try out amending your schema to `posts: [Post!]!`

**Comment by develomark** [comment]
@plck hmmm according to the graphql spec http://graphql.org/learn/schema/#lists-and-non-null, I cannot see a reason why that would be invalid. Seems to be a graphcool quirk to me.

I'm going to fix this for you.

**Comment by develomark** [comment]
Fixed please update to latest - `npm i graphql-cli-generate-cli@latest`

**Comment by paulcpk** [comment]
Thanks man, that fixed the issue for me! Cheers for great plugin maintenance 🎉 .

I examined the code and came up with a similar solution, will just stick with your repo for convenience though.

PS: it should be `npm i graphql-cli-generate-fragments@latest` 😉
