### ISSUE TITLE
`generate-fragments` creates empty fragments

### ISSUE THREAD

**Issue by paulcpk** [develomark/graphql-cli-generate-fragments#4]
Hi there 👋,

running `generate-fragments` on the following schema:
```
type User {
  email: String
  id: Int
  name: String
}

type PayloadUser{
  data: User
}

type dataWrapper {
  getUser: PayloadUser
}

type Query {
  dataWrapper: dataWrapper
}
``` 
generates the according fragments:

```# THIS FILE HAS BEEN AUTO-GENERATED BY "graphql-cli-generate-fragments"
# DO NOT EDIT THIS FILE DIRECTLY

# Standard Fragments
# Nested fragments will spread one layer deep


fragment User on User {
  email
  id
  name
}

fragment PayloadUser on PayloadUser {
  data {
    ...UserNoNesting
  }
}

fragment dataWrapper on dataWrapper {
  getUser {
    ...PayloadUserNoNesting
  }
}


# No Relational objects
# No nested fragments


fragment UserNoNesting on User {
  email
  id
  name
}

fragment PayloadUserNoNesting on PayloadUser {
  
}

fragment dataWrapperNoNesting on dataWrapper {
  
}


# Deeply nested Fragments
# Will include n nested fragments
# If there is a recursive relation you will receive a
# "Cannot spread fragment within itself" error when using


fragment UserDeepNesting on User {
  email
  id
  name
}

fragment PayloadUserDeepNesting on PayloadUser {
  data {
    ...User
  }
}

fragment dataWrapperDeepNesting on dataWrapper {
  getUser {
    ...PayloadUser
  }
}
```

As you may notice, `PayloadUserNoNesting` and `dataWrapperNoNesting` are empty, which throws an error in graphql.

I was able to circumvent this by commenting out a 'return null' case in GenerateFragments.ts, like so https://github.com/plck/graphql-cli-generate-fragments/blob/master/src/GenerateFragments.ts#L391
then the fragments aren't empty anymore.
Ideally the logic should be tweaked a bit, so that `dataWrapperNoNesting` isn't generated at all, since it's never used. I couldn't wrap my head around this so far though.

Any ideas on how to approach this?

Thanks!

**Comment by develomark** [comment]
@plck - yes I can see the issue here. It will require some thought.

By the way, I released a newer version whereby you should see the following output for `dataWrapperDeepnesting`:

```
fragment dataWrapperDeepNesting on dataWrapper {
  getUser {
    ...PayloadUserDeepNesting
  }
}
```

For how I am using it, the empty fragments are not an issue, as I filter after. I do agree we should not be generating empty fragments. This will require some thinking about the solution however.

What I am considering is making the "DeepNesting" fragments the default - so that all levels are spread by default. You would use that in the first instance unless you see a "Cannot spread fragment within itself"  error, in which case the user would switch to `nonesting`.

Thoughts?

**Comment by paulcpk** [comment]
@develomark ok great, then I'll grab the latest version.

I'll have to take a closer look at how the different nesting types work together. I'll give you a heads up in case I come up with something 🙂.

**Comment by paulcpk** [comment]
Hey Mark,
I created a quick fix for the empty fragments, here's the PR https://github.com/develomark/graphql-cli-generate-fragments/pull/7

I understand this is not an elegant solution, but this solved the problem for me so far. 

Any concerns? Let me know what you think!
