### ISSUE TITLE
How to debug Error: Cannot read property 'name' of null 

### ISSUE THREAD

**Issue by bskern** [develomark/graphql-cli-generate-fragments#6]
Hello,

I saw the previously closed issue and running into same thing running off latest. I have a really large schema and not even sure where to start looking for this issue. 

Thanks,
Barry

**Comment by bskern** [comment]
The odd thing I notice is this line prints twice `Generating fragments for project xxx` the first line I can't tell what is supposed to print to the left of that statemtn but it looks green then the second line i see a red x

my npm dependencies are : 
```
  "dependencies": {
    "fetch-graphql-schema": "^0.2.1",
    "graphql": "^0.13.1",
    "graphql-cli-generate-fragments": "^1.1.8"
  }
```

<img width="289" alt="screen shot 2018-02-19 at 5 06 36 pm" src="https://user-images.githubusercontent.com/6706050/36400583-5f1b063e-1597-11e8-90ad-7e64c36f25ec.png">

trying to use the graphql generator from a schema I pulled down and stored locally via fetch doing an introspection query then feeding that into buildClientSchema and finally  printSchema from graphql/utilities

my graphql config 

```
{
  "projects": {
    "tom": {
      "schemaPath": "src/schemas/tom.graphql",
      "extensions": {
        "generate-fragments": {
          "output": "src/generated/tom.fragments.graphql",
          "generator": "graphql"
        }
      }
    }
  }
}
```

**Comment by develomark** [comment]
@bskern can you share your schema?

Have you tried running `graphql init` and letting graphql-cli build your schema automatically from your graphql endpoint?

I wonder if there is something erroneous creeping into the schema you are generating?

**Comment by bskern** [comment]
So I re-did my graphql config via `graphql init` and loaded the schemas via their command but still running into same issue. Unfortunately, I can't post my schema I will try to debug this further

**Comment by develomark** [comment]
@bskern Any joy debugging further?
